### ISSUE TITLE
compilation error on java 1.7

### ISSUE THREAD

**Issue by grobbie** [dell-oss/Mensa#3]
Hello
When I compile mensa using java 1.7 it bombs with this error

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project mensa: Compilation failure
[ERROR] /Users/rob/code/Mensa/mensa/src/main/java/com/dell/mensa/impl/generic/AhoCorasickMachine.java:[807,17] com.dell.mensa.impl.generic.AhoCorasickMachine.MatchIterator is not abstract and does not override abstract method remove() in java.util.Iterator

If I use java 1.8 it compiles ok.

See here for an explanation:
http://stackoverflow.com/questions/5425130/java-iterator-implementation-compile-error-does-not-override-abstract-method-re

You can insert a default implementation such as this at somewhere like line 862 of AhoCorasickMachine.java:

@Override
public void remove() {
    throw new UnsupportedOperationException();
}
 
Then it compiles and all tests pass under java 1.7 (for me)

**Comment by faseidl** [comment]
Thanks, Rob!

Even thought the pom.xml is set to target 1.7, I was compiling with 1.8 and never noticed this issue.

I've added the remove() method per your suggestion.
